### ISSUE TITLE
XDDDDDDDDDDDDDD

### ISSUE THREAD

**Issue by RutsuKun** [Kimjunseo319/Walker#1]
Js sucks for game servers. Change my mind if you can.

**Comment by Kimjunseo319** [comment]
Sorry for my late reply ^^;
As you said, I know JavaScript is bad for game servers :(
But I just wanted to make it out of personal curiosity :)
Thanks for your interest in this little project

**Comment by RutsuKun** [comment]
Good luck with the server 😀
