### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by Miraerin** [Kimjunseo319/Walker#2]
How do i create an account, where do i need to input the "strings" to?
When i try to login from the game i get this:

test test 00-00-00-00-00-00
node:events:353
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'Password' of null
    at C:\Users\vm\Desktop\Walker-main\src\Server\Login\LoginHandler.js:36:19
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\model.js:4843:16
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\model.js:4843:16
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\model.js:4866:21
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\query.js:4410:11
    at C:\Users\vm\Desktop\Walker-main\node_modules\kareem\index.js:135:16
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
    at runNextTicks (node:internal/process/task_queues:62:3)
    at processImmediate (node:internal/timers:436:9)
Emitted 'error' event on Function instance at:
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\model.js:4845:13
    at C:\Users\vm\Desktop\Walker-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    [... lines matching original stack trace ...]
    at processImmediate (node:internal/timers:436:9)

**Comment by Kimjunseo319** [comment]
You have to create an account directly from the accounts collection in the database

**Comment by Miraerin** [comment]
Also do i need to manually create the collections or is there a way to do it automatically?

**Comment by Kimjunseo319** [comment]
You probably have to create it manually.
Like this:
![image](https://user-images.githubusercontent.com/59918240/100683709-3f12d880-33bc-11eb-98a5-642b497cf75f.png)
(Password must be encrypted and value entered)

**Comment by Miraerin** [comment]
Okay i created the account and character, but when i press game start it loads a bit and then it either crashes or i get an ERROR: File '' not found.
![Capture](https://user-images.githubusercontent.com/66223396/100904628-dfa5ed00-34cf-11eb-8cac-71911e9ebc85.PNG)
![Capture1](https://user-images.githubusercontent.com/66223396/100904648-e3d20a80-34cf-11eb-8347-f33cb35df05d.PNG)

Maybe it's my client? i have client's ver:  1.7.47.5, 1.7.47.9, 1.7.48.13 and 1.7.49.4

Or maybe something to do with XignCode3?

**Comment by Kimjunseo319** [comment]
Sorry, I haven't committed yet because I'm having a hard time developing the game server part.
So, the game server part is under development
I'll post progress on GitHub in the future.
If you don't mind, could you send the client?

**Comment by Miraerin** [comment]
Sure, here ya go
https://mega.nz/file/1dkjzAYA#klQaF1b8DkvO9gTSgYTv9o-D7uM57pKICydjQsxsWI0

Hope you figure it out
Good luck with the development.

**Comment by Kimjunseo319** [comment]
Thanks for your interest in this project and thanks for sharing your client
